name: linux
on: push

jobs:
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: format
        run: ./scripts/format.sh && ./scripts/error_on_dirty.sh


  linux_debug_64:
    needs: lint
    name: debug 64bit
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: dependencies
      run: sudo docker/install-shared-deps.sh && mkdir ${{runner.workspace}}/build

    - name: cmake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug

    - name: build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make all -j $(nproc)

    - name: test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: check -j$(nproc)
