name: linux
on: push

jobs:
  linux_debug_64:
    name: Lint code base
    runs-on: ubuntu-20.04
    container: valhalla/valhalla:build-latest
    steps:
      - uses: actions/checkout@v2

      - name: format
        run: |
          ./scripts/format.sh && ./scripts/error_on_dirty.sh

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-debug-linux-x86_64-${GITHUB_REF}
          restore-keys: |
            ccache-debug-linux-x86_64-${GITHUB_REF}
            ccache-debug-linux-x86_64-

      # NOTE: -Werror disabled in CI, as we currently have >4k warnings.
      - name: cmake
        run: mkdir build
        run: cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On -DCPACK_GENERATOR=DEB \
                -DENABLE_COMPILER_WARNINGS=On -DENABLE_WERROR=Off -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
                -DENABLE_PYTHON_BINDINGS=On

      - name: build
        run: make -C build all -j$(nproc)

      - name: tidy
        run: scripts/clang-tidy-only-diff.sh $(nproc)

      - name: package
        run: make -C build install
        run: make -C build package

      # Note: run (compile) tests and make code coverage report.
      - name: coverage
        run: make -C build coverage -j$(nproc)
        run: /bin/bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
