name: linux
on: push

jobs:
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: format
        run: ./scripts/format.sh && ./scripts/error_on_dirty.sh


  linux_debug_64:
    needs: lint
    name: linux debug tidy
    runs:
      using: 'docker'
      image: 'docker/Dockerfile-ci'
